- name: Install APT packages
  apt:
    pkg:
     - python-pip
     - nginx
    update_cache: yes
    state: present
  
- name: Copy appication 
  copy:
    src: /vagrant/flask-hello-world/
    dest: /home/vagrant/flask-hello-world
    force: no
      
- name: Install Python packages
  pip: 
    name:
      - Flask
      - gunicorn
    
- name: Copy configuration
  copy: 
    src: /home/vagrant/flask-hello-world/hello-world.conf 
    dest: /etc/init/hello-world.conf
    force: no

- name: Make sure our server is running
  service: 
    name: hello-world 
    state: started 
    enabled: yes