---
- hosts: all
  become: true
  tasks:    
    - name: Install Packages
      apt: update_cache=yes pkg={{ packages }} state=present
      vars:
        packages:
          - git
          - python-pip
          - nginx
      
    - name: Copy app
      copy: src=/vagrant/flask-hello-world/ dest=/home/vagrant/flask-hello-world
      
    - name: Install requirements
      pip: requirements=/home/vagrant/flask-hello-world/requirements.txt
    
    - name: Copy configuration
      copy: src=/home/vagrant/flask-hello-world/hello-world.conf dest=/etc/init/hello-world.conf

    - name: Make sure our server is running
      service: name=hello-world state=started